version: "3"
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    networks:
      - punch
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  punch:
    build: .
    image: punch
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - punch
    environment:
      MONGODB_URI: mongodb://mongo:mongo@localhost:27017/

networks:
  punch:
    driver: bridge
